[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "buckethandler"
version = "0.9.4"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
	{name = "Jesse Janzer", email = "jjanzer@gmail.com"}
]

dependencies = [
	"requests"
]

[project.optional-dependencies]
# dropbox support requires the dropbox pip package
dropbox = [
	"dropbox>=12.0.0",
]

[project.scripts]
bh = "buckethandler.cli:main"

[project.urls]
Homepage = "https://github.com/jjanzer/buckethandler"
